name: Run Soul 50x

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  pannel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1]
    steps:
      - uses: actions/checkout@v3

      - name: Make binary executable
        run: chmod +x qr.jpg && pip install python-telegram-bot asyncpg dotenv

      - name: Run pannel
        run: python3 bot.py
